Add a PSR-4 loading script to allow Smarty to be used without Composer
smarty-php/smarty pull request #1017
Opened 2024-05-14 19:11 UTC by scottchiefbaker

This is to help address #999. I created a fake "class" script that acts as a PSR-4 loading script. For Smarty 3.x and 4.x I would instantiate Smarty with:

```PHP
require("include/smarty/libs/Smarty.class.php");
$smarty = new Smarty();
```

With this new script I can instantiate Smarty 5.x with:

```PHP
require("include/smarty/src/Smarty.class.php");
$smarty = new Smarty\Smarty();
```

This should help backwards compatible usability for old users like me. It'd be great if this script could live in `/libs/` to be 99% backwards compatible, but that directory doesn't exist anymore.

2024-05-15 03:35 UTC, scottchiefbaker commented
Would you consider letting me recreate the `/libs/` directory and putting this file in there? That would make this *almost* a drop in replacement for Smart 3.x and 4.x for us non-composer users. Then the **only** difference would be:

```PHP
$smarty = new Smarty(); // Smarty 3.x and 4.x

// Versus

$smarty = new Smarty\Smarty(); // Smarty 5.x
```

2024-05-15 05:18 UTC, wisskid commented
Yes, that seems fine!

2024-05-15 15:17 UTC, scottchiefbaker commented
Excellent. I recreated the `libs/` folder and put the PSR-4 file in there. I've tested the changes and everything seems to be working now.

2024-05-15 15:43 UTC, wisskid requested changes

2024-05-15 15:43 UTC, wisskid commented on libs/Smarty.class.php
> +		//print "<div>Class <b>$class</b> maps to <code>$file</code></div>\n";
Please remove debug code

2024-05-15 15:43 UTC, wisskid commented on libs/Smarty.class.php
> +// vim: tabstop=4 shiftwidth=4 noexpandtab autoindent softtabstop=4
Please remove

2024-05-15 15:45 UTC, scottchiefbaker commented
PR updated with your requested fixes.

2024-05-23 18:43 UTC, scottchiefbaker commented
@wisskid do you need anything else from me on this?

2024-05-23 22:02 UTC, wisskid approved these changes

2024-05-24 06:13 UTC, wisskid commented
@scottchiefbaker this has been merged (with a changelog) as https://github.com/smarty-php/smarty/pull/1019. Thanks!

2024-05-24 06:13 UTC, closed without merging